version: "3.3"

services:
  web-portal:
    container_name: web-portal
    image: ghcr.io/enchant97/web-portal:1
    restart: unless-stopped
    volumes:
      - web-portal:/data
    ports:
      - 8000:8000
    environment:
      - "DB_URI=sqlite:///data/db.sqlite"
      # This must be secure
      - "SECRET_KEY=my_super_secret_123"

volumes:
  web-portal:
