# ** IMPORTANT **
# This is to host a demo
# please read the docs on how to deploy
version: "3"

services:
  web-portal:
    container_name: demo-web-portal
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - "DB_URI=sqlite://:memory:"
      - "PLUGIN_SKIP_LIST=[\"core_extras\"]"
      - "ALLOW_ICON_UPLOADS=0"
      - "UNATTENDED_DEMO_INSTALL=1"
