version: "3.3"

services:
  web-portal:
    container_name: web-portal
    build: .
    restart: unless-stopped
    volumes:
      - ./.env:/.env:ro
      - web-portal:/data
    ports:
      - 8000:8000

volumes:
  web-portal:
