[project]
site_name = "Web Portal"
site_url = "https://webportal.docs.enchantedcode.co.uk/"
repo_url = "https://github.com/enchant97/web-portal"
site_author = "Leo Spratt"
copyright = "Copyright © 2022 Leo Spratt under FDLv1.3-or-later"
nav = [
    {"Home" = "index.md"},
    {"User Guide" = [
        "users/index.md",
        "users/install.md",
        "users/usage.md",
        "users/upgrading.md",
        "users/administration.md",
    ]},
    {"Developer Guide" = [
        "developers/index.md",
        "developers/building-plugins.md",
        "developers/plugin-reference.md"
    ]}
]

[project.theme]
features = [
    "navigation.instant",
    "navigation.expand",
    "navigation.path"
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["web_portal"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "sphinx"
inherited_members = true
show_source = false
