name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, next ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install Tools
      run: |
        pip install hatch
    - name: Run Linter
      run: |
        hatch run dev:lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install Tools
      run: |
        pip install hatch
    - name: Run Tests
      run: |
        hatch run dev:unit-test

  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install Tools
      run: |
        pip install hatch
        hatch run deps
        hatch run dev:e2e-deps
    - name: Run Tests
      run: hatch run dev:e2e-test
    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/
